###
PUT http://127.0.0.1:5000/v1/hobbies/2 HTTP/1.1
Content-Type: application/json

{
    "name": "hello2"
}

###
POST http://127.0.0.1:5000/v1/hobbies HTTP/1.1
Content-Type: application/json

{
    "name": "new Hobby"
}
